// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/start-client-core";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env["SUPABASE_URL"];
    const SUPABASE_PUBLISHABLE_KEY = process.env["SUPABASE_PUBLISHABLE_KEY"];

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Configure the WTRON production Supabase environment.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();
    const diagnostic = request?.headers?.get("x-wtron-auth-diagnostic") ?? null;
    const logDiagnostic = (stage: string, details?: Record<string, unknown>) => {
      if (!diagnostic) return;
      console.info(`[AdminAuth] ${stage}`, { diagnostic, ...(details ?? {}) });
    };

    if (!request?.headers) {
      logDiagnostic("SERVER_AUTH_FAIL", { reason: "missing_headers" });
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      logDiagnostic("SERVER_AUTH_FAIL", { reason: "missing_authorization_header" });
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      logDiagnostic("SERVER_AUTH_FAIL", { reason: "unsupported_authorization_scheme" });
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      logDiagnostic("SERVER_AUTH_FAIL", { reason: "empty_bearer_token" });
      throw new Error("Unauthorized: No token provided");
    }

    if (token.split(".").length !== 3) {
      logDiagnostic("SERVER_AUTH_FAIL", { reason: "malformed_bearer_token" });
      throw new Error("Unauthorized: Invalid token");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const claimsResult = await supabase.auth.getClaims(token);
    const claims = claimsResult.data?.claims;
    let userId = claims?.sub;
    if (claimsResult.error || !userId) {
      const userResult = await supabase.auth.getUser(token);
      if (userResult.error || !userResult.data.user) {
        logDiagnostic("SERVER_AUTH_FAIL", { reason: "supabase_token_rejected" });
        throw new Error("Unauthorized: Invalid token");
      }
      userId = userResult.data.user.id;
    }

    if (!userId) {
      logDiagnostic("SERVER_AUTH_FAIL", { reason: "missing_user_id" });
      throw new Error("Unauthorized: No user ID found in token");
    }
    logDiagnostic("SERVER_AUTH_SUCCESS", { userIdPresent: true });

    return next({
      context: {
        supabase,
        userId,
        claims: claims ?? { sub: userId },
      },
    });
  },
);
