// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { isAuthoritativeSupabaseUrl } from "@/lib/production-url";

declare global {
  interface Window {
    __WTRON_PUBLIC_CONFIG__?: {
      supabaseUrl?: string;
      supabasePublishableKey?: string;
    };
  }
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const runtimeConfig = typeof window !== "undefined" ? window.__WTRON_PUBLIC_CONFIG__ : undefined;
  const candidates = [
    {
      url: runtimeConfig?.supabaseUrl,
      key: runtimeConfig?.supabasePublishableKey,
    },
    {
      url: import.meta.env["VITE_SUPABASE_URL"],
      key: import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"],
    },
    {
      url: process.env["SUPABASE_URL"],
      key: process.env["SUPABASE_PUBLISHABLE_KEY"],
    },
  ];
  const authoritative = candidates.find(
    (candidate) => isAuthoritativeSupabaseUrl(candidate.url) && candidate.key,
  );
  const SUPABASE_URL = authoritative?.url;
  const SUPABASE_PUBLISHABLE_KEY = authoritative?.key;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing authoritative Supabase environment variable(s): ${missing.join(", ")}. WTRON requires project taqdmbcqztxwdgkwfcoi.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
